apiVersion: surrealdb.seamlezz.com/v1alpha1
kind: SurrealDBProvider
metadata:
  labels:
    app.kubernetes.io/name: surrealdb-credential-operator
    app.kubernetes.io/managed-by: kustomize
  name: surrealdbprovider-sample
spec:
  # TODO(user): Add fields here
