//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASecretReference) DeepCopyInto(out *CASecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASecretReference.
func (in *CASecretReference) DeepCopy() *CASecretReference {
	if in == nil {
		return nil
	}
	out := new(CASecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientCertificateReference) DeepCopyInto(out *ClientCertificateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientCertificateReference.
func (in *ClientCertificateReference) DeepCopy() *ClientCertificateReference {
	if in == nil {
		return nil
	}
	out := new(ClientCertificateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseUserPolicy) DeepCopyInto(out *DatabaseUserPolicy) {
	*out = *in
	if in.AllowedDatabases != nil {
		in, out := &in.AllowedDatabases, &out.AllowedDatabases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedRoles != nil {
		in, out := &in.AllowedRoles, &out.AllowedRoles
		*out = make([]SurrealRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseUserPolicy.
func (in *DatabaseUserPolicy) DeepCopy() *DatabaseUserPolicy {
	if in == nil {
		return nil
	}
	out := new(DatabaseUserPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPolicyReference) DeepCopyInto(out *LocalPolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPolicyReference.
func (in *LocalPolicyReference) DeepCopy() *LocalPolicyReference {
	if in == nil {
		return nil
	}
	out := new(LocalPolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalProviderReference) DeepCopyInto(out *LocalProviderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalProviderReference.
func (in *LocalProviderReference) DeepCopy() *LocalProviderReference {
	if in == nil {
		return nil
	}
	out := new(LocalProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceUserPolicy) DeepCopyInto(out *NamespaceUserPolicy) {
	*out = *in
	if in.AllowedRoles != nil {
		in, out := &in.AllowedRoles, &out.AllowedRoles
		*out = make([]SurrealRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceUserPolicy.
func (in *NamespaceUserPolicy) DeepCopy() *NamespaceUserPolicy {
	if in == nil {
		return nil
	}
	out := new(NamespaceUserPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretReference) DeepCopyInto(out *NamespacedSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretReference.
func (in *NamespacedSecretReference) DeepCopy() *NamespacedSecretReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderTLSConfig) DeepCopyInto(out *ProviderTLSConfig) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(CASecretReference)
		**out = **in
	}
	if in.ClientCertificateRef != nil {
		in, out := &in.ClientCertificateRef, &out.ClientCertificateRef
		*out = new(ClientCertificateReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderTLSConfig.
func (in *ProviderTLSConfig) DeepCopy() *ProviderTLSConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootCredentialReference) DeepCopyInto(out *RootCredentialReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootCredentialReference.
func (in *RootCredentialReference) DeepCopy() *RootCredentialReference {
	if in == nil {
		return nil
	}
	out := new(RootCredentialReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationSpec) DeepCopyInto(out *RotationSpec) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationSpec.
func (in *RotationSpec) DeepCopy() *RotationSpec {
	if in == nil {
		return nil
	}
	out := new(RotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBCredential) DeepCopyInto(out *SurrealDBCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBCredential.
func (in *SurrealDBCredential) DeepCopy() *SurrealDBCredential {
	if in == nil {
		return nil
	}
	out := new(SurrealDBCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBCredentialList) DeepCopyInto(out *SurrealDBCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SurrealDBCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBCredentialList.
func (in *SurrealDBCredentialList) DeepCopy() *SurrealDBCredentialList {
	if in == nil {
		return nil
	}
	out := new(SurrealDBCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBCredentialSpec) DeepCopyInto(out *SurrealDBCredentialSpec) {
	*out = *in
	out.PolicyRef = in.PolicyRef
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]SurrealRole, len(*in))
		copy(*out, *in)
	}
	out.TargetSecret = in.TargetSecret
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(RotationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBCredentialSpec.
func (in *SurrealDBCredentialSpec) DeepCopy() *SurrealDBCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(SurrealDBCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBCredentialStatus) DeepCopyInto(out *SurrealDBCredentialStatus) {
	*out = *in
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(LocalProviderReference)
		**out = **in
	}
	if in.LastRotationTime != nil {
		in, out := &in.LastRotationTime, &out.LastRotationTime
		*out = (*in).DeepCopy()
	}
	if in.NextRotationTime != nil {
		in, out := &in.NextRotationTime, &out.NextRotationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBCredentialStatus.
func (in *SurrealDBCredentialStatus) DeepCopy() *SurrealDBCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(SurrealDBCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBProvider) DeepCopyInto(out *SurrealDBProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBProvider.
func (in *SurrealDBProvider) DeepCopy() *SurrealDBProvider {
	if in == nil {
		return nil
	}
	out := new(SurrealDBProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBProviderList) DeepCopyInto(out *SurrealDBProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SurrealDBProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBProviderList.
func (in *SurrealDBProviderList) DeepCopy() *SurrealDBProviderList {
	if in == nil {
		return nil
	}
	out := new(SurrealDBProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBProviderSpec) DeepCopyInto(out *SurrealDBProviderSpec) {
	*out = *in
	out.RootCredentialRef = in.RootCredentialRef
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ProviderTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBProviderSpec.
func (in *SurrealDBProviderSpec) DeepCopy() *SurrealDBProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SurrealDBProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBProviderStatus) DeepCopyInto(out *SurrealDBProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBProviderStatus.
func (in *SurrealDBProviderStatus) DeepCopy() *SurrealDBProviderStatus {
	if in == nil {
		return nil
	}
	out := new(SurrealDBProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBTenantPolicy) DeepCopyInto(out *SurrealDBTenantPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBTenantPolicy.
func (in *SurrealDBTenantPolicy) DeepCopy() *SurrealDBTenantPolicy {
	if in == nil {
		return nil
	}
	out := new(SurrealDBTenantPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBTenantPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBTenantPolicyList) DeepCopyInto(out *SurrealDBTenantPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SurrealDBTenantPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBTenantPolicyList.
func (in *SurrealDBTenantPolicyList) DeepCopy() *SurrealDBTenantPolicyList {
	if in == nil {
		return nil
	}
	out := new(SurrealDBTenantPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SurrealDBTenantPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBTenantPolicySpec) DeepCopyInto(out *SurrealDBTenantPolicySpec) {
	*out = *in
	out.ProviderRef = in.ProviderRef
	in.DatabaseUsers.DeepCopyInto(&out.DatabaseUsers)
	in.NamespaceUsers.DeepCopyInto(&out.NamespaceUsers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBTenantPolicySpec.
func (in *SurrealDBTenantPolicySpec) DeepCopy() *SurrealDBTenantPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SurrealDBTenantPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurrealDBTenantPolicyStatus) DeepCopyInto(out *SurrealDBTenantPolicyStatus) {
	*out = *in
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(LocalProviderReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurrealDBTenantPolicyStatus.
func (in *SurrealDBTenantPolicyStatus) DeepCopy() *SurrealDBTenantPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SurrealDBTenantPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecretSpec) DeepCopyInto(out *TargetSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSecretSpec.
func (in *TargetSecretSpec) DeepCopy() *TargetSecretSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSecretSpec)
	in.DeepCopyInto(out)
	return out
}
