replicaCount: 1

image:
  repository: ghcr.io/seamlezz/surrealdb-credential-operator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

leaderElection:
  enabled: true

metrics:
  bindAddress: ":8443"
  secure: true

health:
  probeBindAddress: ":8081"
